/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoprogra;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author da_he
 */
public class End extends javax.swing.JFrame {
private Jugador jugador;
    /**
     * Creates new form End
     */
    FondoPanel fondo = new FondoPanel();
    public End() {
        this.setContentPane(fondo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AnteriorCarrito = new javax.swing.JButton();
        Fondo1 = new javax.swing.JPanel();
        Fondo2 = new javax.swing.JPanel();
        AnteriorCarrito1 = new javax.swing.JButton();
        Fondo3 = new javax.swing.JPanel();
        AnteriorEnd = new javax.swing.JButton();
        EndMessage = new java.awt.TextArea();

        AnteriorCarrito.setBackground(new java.awt.Color(166, 124, 82));
        AnteriorCarrito.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AnteriorCarrito.setForeground(new java.awt.Color(255, 255, 255));
        AnteriorCarrito.setText("Anterior");
        AnteriorCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorCarritoActionPerformed(evt);
            }
        });

        Fondo1.setBackground(new java.awt.Color(235, 218, 193));
        Fondo1.setForeground(new java.awt.Color(166, 124, 82));

        Fondo2.setBackground(new java.awt.Color(235, 218, 193));
        Fondo2.setForeground(new java.awt.Color(166, 124, 82));

        AnteriorCarrito1.setBackground(new java.awt.Color(166, 124, 82));
        AnteriorCarrito1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AnteriorCarrito1.setForeground(new java.awt.Color(255, 255, 255));
        AnteriorCarrito1.setText("Anterior");
        AnteriorCarrito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorCarrito1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Fondo2Layout = new javax.swing.GroupLayout(Fondo2);
        Fondo2.setLayout(Fondo2Layout);
        Fondo2Layout.setHorizontalGroup(
            Fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AnteriorCarrito1)
                .addContainerGap(645, Short.MAX_VALUE))
        );
        Fondo2Layout.setVerticalGroup(
            Fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo2Layout.createSequentialGroup()
                .addContainerGap(445, Short.MAX_VALUE)
                .addComponent(AnteriorCarrito1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Fondo1Layout = new javax.swing.GroupLayout(Fondo1);
        Fondo1.setLayout(Fondo1Layout);
        Fondo1Layout.setHorizontalGroup(
            Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo1Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(Fondo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        Fondo1Layout.setVerticalGroup(
            Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(Fondo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo3.setBackground(new java.awt.Color(235, 218, 193));
        Fondo3.setForeground(new java.awt.Color(166, 124, 82));

        AnteriorEnd.setBackground(new java.awt.Color(166, 124, 82));
        AnteriorEnd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AnteriorEnd.setForeground(new java.awt.Color(255, 255, 255));
        AnteriorEnd.setText("Anterior");
        AnteriorEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorEndActionPerformed(evt);
            }
        });

        EndMessage.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout Fondo3Layout = new javax.swing.GroupLayout(Fondo3);
        Fondo3.setLayout(Fondo3Layout);
        Fondo3Layout.setHorizontalGroup(
            Fondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AnteriorEnd)
                .addContainerGap(645, Short.MAX_VALUE))
            .addGroup(Fondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Fondo3Layout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(EndMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(114, Short.MAX_VALUE)))
        );
        Fondo3Layout.setVerticalGroup(
            Fondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo3Layout.createSequentialGroup()
                .addContainerGap(445, Short.MAX_VALUE)
                .addComponent(AnteriorEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(Fondo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Fondo3Layout.createSequentialGroup()
                    .addGap(134, 134, 134)
                    .addComponent(EndMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(134, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(Fondo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(Fondo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnteriorCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorCarritoActionPerformed
        
    }//GEN-LAST:event_AnteriorCarritoActionPerformed

    private void AnteriorCarrito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorCarrito1ActionPerformed
        
    }//GEN-LAST:event_AnteriorCarrito1ActionPerformed

    private void AnteriorEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorEndActionPerformed
        // TODO add your handling code here:
        Shop sig = new Shop(jugador);
        sig.setVisible(true);
        sig.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_AnteriorEndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(End.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(End.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(End.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(End.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new End().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnteriorCarrito;
    private javax.swing.JButton AnteriorCarrito1;
    private javax.swing.JButton AnteriorEnd;
    private java.awt.TextArea EndMessage;
    private javax.swing.JPanel Fondo1;
    private javax.swing.JPanel Fondo2;
    private javax.swing.JPanel Fondo3;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JButton jButton1;

    class FondoPanel extends JPanel {
        private Image imagen;

        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (imagen == null) {
                imagen = new ImageIcon(getClass().getResource("/Imagenes/Super_interacciones.png")).getImage();
            }
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        }
    }
}
