/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoprogra;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author da_he
 */
public class Shop extends javax.swing.JFrame {
    private Jugador jugador;
    /**
     * Creates new form Shop
     */
    FondoPanel fondo = new FondoPanel();
    public Shop(Jugador jugador) {
        this.setContentPane(fondo);
        this.jugador = jugador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo1 = new javax.swing.JPanel();
        Before1 = new javax.swing.JButton();
        Fondo2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Next1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        Fondo3 = new javax.swing.JPanel();
        Next2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Next3 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        Fondo4 = new javax.swing.JPanel();
        SuperTab = new javax.swing.JButton();
        ListaTab = new javax.swing.JButton();
        CarritoTab = new javax.swing.JButton();
        EndTab = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Panel = new javax.swing.JTextPane();

        Fondo1.setBackground(new java.awt.Color(235, 218, 193));

        Before1.setBackground(new java.awt.Color(166, 124, 82));
        Before1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Before1.setText("Anterior");
        Before1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Before1ActionPerformed(evt);
            }
        });

        Fondo2.setBackground(new java.awt.Color(235, 218, 193));
        Fondo2.setForeground(new java.awt.Color(166, 124, 82));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(74, 44, 42));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");

        Next1.setBackground(new java.awt.Color(166, 124, 82));
        Next1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Next1.setForeground(new java.awt.Color(255, 255, 255));
        Next1.setText("Siguiente");
        Next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next1ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(74, 44, 42));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tu mamá te acaba de enviar al supermercado a comprar ciertos productos. ");

        jLabel3.setForeground(new java.awt.Color(74, 44, 42));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tienes una lista de compras y un presupuesto. Si compras correctamente todo lo que te pidió, ¡ganarás!");

        jLabel4.setForeground(new java.awt.Color(74, 44, 42));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pero si compras demasiado o no traes lo que te pidio, perderás y tu mama te va a pegar ");

        jLabel5.setForeground(new java.awt.Color(74, 44, 42));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("\"¡Bienvenido al Supermercado! ");

        javax.swing.GroupLayout Fondo2Layout = new javax.swing.GroupLayout(Fondo2);
        Fondo2.setLayout(Fondo2Layout);
        Fondo2Layout.setHorizontalGroup(
            Fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo2Layout.createSequentialGroup()
                .addGroup(Fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Next1))
                    .addGroup(Fondo2Layout.createSequentialGroup()
                        .addGroup(Fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Fondo2Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel3))
                            .addGroup(Fondo2Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel4))
                            .addGroup(Fondo2Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel2))
                            .addGroup(Fondo2Layout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addGroup(Fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Fondo2Layout.setVerticalGroup(
            Fondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(Next1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Fondo1Layout = new javax.swing.GroupLayout(Fondo1);
        Fondo1.setLayout(Fondo1Layout);
        Fondo1Layout.setHorizontalGroup(
            Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Before1)
                .addContainerGap(639, Short.MAX_VALUE))
            .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Fondo1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Fondo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        Fondo1Layout.setVerticalGroup(
            Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo1Layout.createSequentialGroup()
                .addContainerGap(435, Short.MAX_VALUE)
                .addComponent(Before1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Fondo1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Fondo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(74, 44, 42));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Bienvenido");

        jLabel10.setForeground(new java.awt.Color(74, 44, 42));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("\"¡Bienvenido al Supermercado! ");

        jLabel7.setForeground(new java.awt.Color(74, 44, 42));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tu mamá te acaba de enviar al supermercado a comprar ciertos productos. ");

        jLabel8.setForeground(new java.awt.Color(74, 44, 42));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tienes una lista de compras y un presupuesto. Si compras correctamente todo lo que te pidió, ¡ganarás!");

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Fondo3.setBackground(new java.awt.Color(235, 218, 193));
        Fondo3.setForeground(new java.awt.Color(166, 124, 82));
        Fondo3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Next2.setBackground(new java.awt.Color(166, 124, 82));
        Next2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Next2.setForeground(new java.awt.Color(255, 255, 255));
        Next2.setText("Siguiente");
        Next2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next2ActionPerformed(evt);
            }
        });
        Fondo3.add(Next2, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 445, -1, 34));

        jButton2.setText("jButton2");
        Fondo3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 142, -1, -1));

        jButton3.setText("jButton3");
        Fondo3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 181, -1, -1));

        jButton5.setText("jButton5");
        Fondo3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        jButton6.setText("jButton6");

        jButton7.setText("jButton7");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(74, 44, 42));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Bienvenido");

        jLabel14.setForeground(new java.awt.Color(74, 44, 42));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("\"¡Bienvenido al Supermercado! ");

        jLabel11.setForeground(new java.awt.Color(74, 44, 42));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Tu mamá te acaba de enviar al supermercado a comprar ciertos productos. ");

        jLabel12.setForeground(new java.awt.Color(74, 44, 42));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Tienes una lista de compras y un presupuesto. Si compras correctamente todo lo que te pidió, ¡ganarás!");

        jLabel13.setForeground(new java.awt.Color(74, 44, 42));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Pero si compras demasiado o no traes lo que te pidio, perderás y tu mama te va a pegar ");

        Next3.setBackground(new java.awt.Color(166, 124, 82));
        Next3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Next3.setForeground(new java.awt.Color(255, 255, 255));
        Next3.setText("Siguiente");
        Next3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Next3ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(166, 124, 82));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("4. Salir");
        jButton12.setMaximumSize(new java.awt.Dimension(201, 27));
        jButton12.setMinimumSize(new java.awt.Dimension(201, 27));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo4.setBackground(new java.awt.Color(235, 218, 193));
        Fondo4.setForeground(new java.awt.Color(166, 124, 82));

        SuperTab.setBackground(new java.awt.Color(166, 124, 82));
        SuperTab.setForeground(new java.awt.Color(255, 255, 255));
        SuperTab.setText("1. Explorar Supermercado");
        SuperTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuperTabActionPerformed(evt);
            }
        });

        ListaTab.setBackground(new java.awt.Color(166, 124, 82));
        ListaTab.setForeground(new java.awt.Color(255, 255, 255));
        ListaTab.setText("2. Ver lista de mama");
        ListaTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ListaTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaTabActionPerformed(evt);
            }
        });

        CarritoTab.setBackground(new java.awt.Color(166, 124, 82));
        CarritoTab.setForeground(new java.awt.Color(255, 255, 255));
        CarritoTab.setText("3. Ver carrito de compras");
        CarritoTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarritoTabActionPerformed(evt);
            }
        });

        EndTab.setBackground(new java.awt.Color(166, 124, 82));
        EndTab.setForeground(new java.awt.Color(255, 255, 255));
        EndTab.setText("4. Finalizar compra y volver a casa");
        EndTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndTabActionPerformed(evt);
            }
        });

        Panel.setBackground(new java.awt.Color(166, 124, 82));
        Panel.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(Panel);

        javax.swing.GroupLayout Fondo4Layout = new javax.swing.GroupLayout(Fondo4);
        Fondo4.setLayout(Fondo4Layout);
        Fondo4Layout.setHorizontalGroup(
            Fondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo4Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(Fondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Fondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(EndTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(ListaTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CarritoTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(SuperTab, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(224, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        Fondo4Layout.setVerticalGroup(
            Fondo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(SuperTab, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ListaTab, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CarritoTab, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EndTab, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(Fondo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(Fondo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Before1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Before1ActionPerformed
    }//GEN-LAST:event_Before1ActionPerformed

    private void Next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next1ActionPerformed

    }//GEN-LAST:event_Next1ActionPerformed

    private void Next2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Next2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Next3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Next3ActionPerformed

    }//GEN-LAST:event_Next3ActionPerformed

    private void SuperTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuperTabActionPerformed
        // TODO add your handling code here:
        Super sig = new Super(jugador);
        sig.setVisible(true);
        sig.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_SuperTabActionPerformed
    
    public void ShowMoney(){
        Panel.setText(String.valueOf("$" +jugador.getDinero()));
    }
    
    private void EndTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndTabActionPerformed
        // TODO add your handling code here:
        End sig = new End();
        sig.setVisible(true);
        sig.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_EndTabActionPerformed

    private void ListaTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaTabActionPerformed
        // TODO add your handling code here:
        Lista sig = new Lista(jugador);
        sig.setVisible(true);
        sig.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_ListaTabActionPerformed

    private void CarritoTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarritoTabActionPerformed
        if (jugador == null) {
            JOptionPane.showMessageDialog(this, "El jugador no está inicializado.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else if (jugador.getTuCarrito().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tu carrito está vacío.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            Carrito sig = new Carrito();
            sig.setVisible(true);
            sig.setLocationRelativeTo(null);
            this.setVisible(false);
        }
    }//GEN-LAST:event_CarritoTabActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Este método ahora solo debe hacer visible la ventana Shop
                // No debes crear un jugador aquí, se debe pasar desde otro JFrame
            }
        });
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Before1;
    private javax.swing.JButton CarritoTab;
    private javax.swing.JButton EndTab;
    private javax.swing.JPanel Fondo1;
    private javax.swing.JPanel Fondo2;
    private javax.swing.JPanel Fondo3;
    private javax.swing.JPanel Fondo4;
    private javax.swing.JButton ListaTab;
    private javax.swing.JButton Next1;
    private javax.swing.JButton Next2;
    private javax.swing.JButton Next3;
    private javax.swing.JTextPane Panel;
    private javax.swing.JButton SuperTab;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
private javax.swing.JButton jButton1;

    class FondoPanel extends JPanel {
        private Image imagen;

        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (imagen == null) {
                imagen = new ImageIcon(getClass().getResource("/Imagenes/Super_interacciones.png")).getImage();
            }
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        }
    }
}
