/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectoprogra;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author da_he
 */
public class Super extends javax.swing.JFrame {
private Jugador jugador;
    /**
     * Creates new form Super
     */
    FondoPanel fondo = new FondoPanel();
    public Super(Jugador jugador) {
        this.setContentPane(fondo);
        initComponents();
        this.jugador = jugador;
        Listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        list1 = new java.awt.List();
        Fondo1 = new javax.swing.JPanel();
        AnteriorSuper = new javax.swing.JButton();
        Objetos = new java.awt.TextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        agregar = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(74, 44, 42));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido");

        jLabel4.setForeground(new java.awt.Color(74, 44, 42));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pero si compras demasiado o no traes lo que te pidio, perderás y tu mama te va a pegar ");

        jLabel3.setForeground(new java.awt.Color(74, 44, 42));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tienes una lista de compras y un presupuesto. Si compras correctamente todo lo que te pidió, ¡ganarás!");

        jLabel2.setForeground(new java.awt.Color(74, 44, 42));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tu mamá te acaba de enviar al supermercado a comprar ciertos productos. ");

        jLabel5.setForeground(new java.awt.Color(74, 44, 42));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("\"¡Bienvenido al Supermercado! ");

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo1.setBackground(new java.awt.Color(235, 218, 193));
        Fondo1.setForeground(new java.awt.Color(166, 124, 82));

        AnteriorSuper.setBackground(new java.awt.Color(166, 124, 82));
        AnteriorSuper.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AnteriorSuper.setForeground(new java.awt.Color(255, 255, 255));
        AnteriorSuper.setText("Anterior");
        AnteriorSuper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorSuperActionPerformed(evt);
            }
        });

        Objetos.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Selecciona que producto deseas");

        lista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", " ", " ", " ", " ", " ", " ", " ", " ", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lista);

        agregar.setBackground(new java.awt.Color(166, 124, 82));
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setText("Agregar");
        agregar.setMaximumSize(new java.awt.Dimension(89, 27));
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Fondo1Layout = new javax.swing.GroupLayout(Fondo1);
        Fondo1.setLayout(Fondo1Layout);
        Fondo1Layout.setHorizontalGroup(
            Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo1Layout.createSequentialGroup()
                .addGroup(Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Fondo1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(Objetos, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Fondo1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AnteriorSuper))
                    .addGroup(Fondo1Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel6))
                    .addGroup(Fondo1Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Fondo1Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        Fondo1Layout.setVerticalGroup(
            Fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Fondo1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(Objetos, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(AnteriorSuper, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(Fondo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(Fondo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnteriorSuperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorSuperActionPerformed
        // TODO add your handling code here:
        Shop sig = new Shop(jugador);
        sig.setVisible(true);
        sig.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_AnteriorSuperActionPerformed
    
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        int productoSeleccionado = lista.getSelectedIndex();
        if (productoSeleccionado == -1){
            JOptionPane.showMessageDialog(this, "Por favor selecciona un producto. Error");
        } 
        else {
            JOptionPane.showMessageDialog(this, Supermercado.products[productoSeleccionado].getNombre() + " ha sido agregado a tu carrito.");
    }
        
    }//GEN-LAST:event_agregarActionPerformed
    
    public int AgregarBasket(){
        int num = lista.getSelectedIndex();
        if (num == -1) { 
            JOptionPane.showMessageDialog(this, "No has seleccionado ningún producto. Error");
            return -1;
        } 
        else {
            return num-1;
        }
    }
    
    
    public void Listar(){
        Objetos.setText("");
        int cont=1;
        for(Producto i: Supermercado.products){
            Objetos.append(cont+". Producto: " + i.getNombre()+" | Precio: $"+i.getPrecio()+"\n");
            cont++;
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Super.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Este main no necesita crear un jugador, ya que debe ser pasado desde otro JFrame
                new Super(null).setVisible(true); // Es solo para el ejemplo, el jugador debe ser pasado desde otro JFrame
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnteriorSuper;
    private javax.swing.JPanel Fondo1;
    private java.awt.TextArea Objetos;
    private javax.swing.JButton agregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTree jTree1;
    private java.awt.List list1;
    private javax.swing.JList<String> lista;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JButton jButton1;

    class FondoPanel extends JPanel {
        private Image imagen;

        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (imagen == null) {
                imagen = new ImageIcon(getClass().getResource("/Imagenes/Super_interacciones.png")).getImage();
            }
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        }
    }
}
